/* Berry Haven Beta Release 1.0
   Phaser-powered Berry Arcade. Designed for Phaser 3.90.x global build.
   Existing DOM games remain as fallback when Phaser is unavailable. */
(function(){
  'use strict';
  if(!window.Phaser){
    console.warn('Berry Arcade: Phaser did not load; classic DOM games remain available.');
    window.BerryArcade={launchSolo:()=>false,resumeActiveSolo:()=>false,renderMultiplayer:()=>false,leaveMultiplayer:()=>{},destroyAll:()=>{}};
    return;
  }
  const W=720,H=820;
  const COLORS={bg:0x180d19,panel:0x2b1528,panel2:0x3a1d36,berry:0xee5a82,berry2:0xff96b4,cream:0xfff3e9,gold:0xf4c85b,blue:0x4f75bd,blue2:0x8aa8ff,green:0x6fa36f,mint:0xa9ddbb,purple:0x8f6cc7,ink:0x432b38,white:0xffffff,dark:0x160b15};
  let soloGame=null,soloKey='',mpGame=null,mpId='';

  function bridge(){return window.BerryBridge||null}
  function phaserReady(){return !!window.Phaser}
  function destroy(game){try{game?.destroy(true)}catch(_){} }
  function stageFor(pane,key){
    let stage=pane.querySelector('.berry-arcade-stage');
    if(!stage){stage=document.createElement('div');stage.className='berry-arcade-stage';stage.dataset.arcade=key;const anchor=pane.querySelector('.game-statbar');if(anchor)anchor.insertAdjacentElement('afterend',stage);else pane.appendChild(stage)}
    const art=window.getBerryGameArt?.(key)?.src;
    stage.style.backgroundImage=art?`linear-gradient(180deg,rgba(18,8,17,.54),rgba(18,8,17,.78)),url("${art}")`:'linear-gradient(160deg,#190c19,#36162f)';
    stage.style.backgroundSize='cover';stage.style.backgroundPosition='center';
    pane.classList.add('beta-phaser');
    return stage
  }
  function makeConfig(parent,scene){return {type:Phaser.AUTO,width:W,height:H,parent,transparent:true,antialias:true,pixelArt:false,roundPixels:false,input:{activePointers:3},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene}}
  function panel(scene,x,y,w,h,color=COLORS.panel,alpha=.88,r=28){const g=scene.add.graphics();g.fillStyle(color,alpha);g.fillRoundedRect(x-w/2,y-h/2,w,h,r);g.lineStyle(2,0xffffff,.10);g.strokeRoundedRect(x-w/2,y-h/2,w,h,r);return g}
  function label(scene,x,y,text,size=28,color='#fff',style={}){return scene.add.text(x,y,text,{fontFamily:'system-ui, sans-serif',fontSize:size,fontStyle:style.fontStyle||'normal',fontWeight:style.weight||'700',color,align:style.align||'center',wordWrap:style.wrap?{width:style.wrap}:undefined}).setOrigin(.5)}
  function pill(scene,x,y,w,h,text,fn,opts={}){const c=scene.add.container(x,y);const bg=scene.add.graphics();bg.fillStyle(opts.color||COLORS.berry,opts.alpha??1);bg.fillRoundedRect(-w/2,-h/2,w,h,h/2);bg.lineStyle(2,0xffffff,.18);bg.strokeRoundedRect(-w/2,-h/2,w,h,h/2);const t=scene.add.text(0,0,text,{fontFamily:'system-ui',fontSize:opts.size||24,fontWeight:'800',color:opts.text||'#fff'}).setOrigin(.5);c.add([bg,t]);c.setSize(w,h);if(fn)c.setInteractive({useHandCursor:true}).on('pointerdown',()=>{scene.tweens.add({targets:c,scale:.95,duration:70,yoyo:true});fn()});return c}
  function sparkle(scene,x,y,color=COLORS.gold,count=12){for(let i=0;i<count;i++){const r=scene.add.circle(x,y,Phaser.Math.Between(3,7),color,1);const a=(Math.PI*2*i/count)+Math.random()*.2,d=Phaser.Math.Between(55,130);scene.tweens.add({targets:r,x:x+Math.cos(a)*d,y:y+Math.sin(a)*d,alpha:0,scale:.2,duration:Phaser.Math.Between(450,850),ease:'Cubic.Out',onComplete:()=>r.destroy()})}}
  function header(scene,title,subtitle){panel(scene,W/2,67,650,92,COLORS.panel,.72,30);label(scene,80,52,'🍓',34);scene.add.text(120,34,title,{fontFamily:'system-ui',fontSize:28,fontWeight:'900',color:'#fff'});scene.add.text(120,67,subtitle,{fontFamily:'system-ui',fontSize:16,fontWeight:'700',color:'#e8cfdd'});}
  function reward(kind,amount,elapsed){const b=bridge();if(!b)return;b.rewardWin?.(kind,amount,elapsed)}
  function message(scene,text,color='#fff'){const t=label(scene,W/2,770,text,20,color,{wrap:610});t.setAlpha(0);scene.tweens.add({targets:t,alpha:1,y:760,duration:240});return t}

  class PairsScene extends Phaser.Scene{
    constructor(){super('pairs')}
    create(){
      header(this,'Berry Pairs','Flip, match and build a sparkling streak');
      this.started=performance.now();this.lock=false;this.first=null;this.matched=0;
      this.timer=label(this,580,120,'0.0s',20,'#ffe3ed');this.progress=label(this,140,120,'0 / 6 pairs',20,'#ffe3ed');
      const symbols=['🍓','🌙','🧸','⭐','🌸','☁️'];
      const deck=Phaser.Utils.Array.Shuffle([...symbols,...symbols].map((s,i)=>({s,id:i,open:false,done:false})));
      this.cards=[];const cols=4,cw=132,ch=150,startX=95,startY=225;
      deck.forEach((card,i)=>{const col=i%cols,row=Math.floor(i/cols),x=startX+col*176,y=startY+row*178;const c=this.add.container(x,y);const g=this.add.graphics();g.fillStyle(COLORS.cream,1);g.fillRoundedRect(-cw/2,-ch/2,cw,ch,26);g.lineStyle(5,COLORS.berry2,.9);g.strokeRoundedRect(-cw/2,-ch/2,cw,ch,26);const back=label(this,0,0,'🍓',52,'#fff');const face=label(this,0,0,card.s,54,'#fff');face.setVisible(false);c.add([g,back,face]);c.setSize(cw,ch).setInteractive({useHandCursor:true});c.card=card;c.face=face;c.back=back;c.on('pointerdown',()=>this.flipCard(c));this.cards.push(c)});
      pill(this,W/2,725,190,54,'Shuffle',()=>this.scene.restart(),{color:COLORS.purple});
    }
    update(){if(this.timer&&this.started)this.timer.setText(((performance.now()-this.started)/1000).toFixed(1)+'s')}
    flipCard(c){if(this.lock||c.card.open||c.card.done)return;this.lock=true;this.tweens.add({targets:c,scaleX:.04,duration:120,ease:'Quad.In',onComplete:()=>{c.card.open=true;c.back.setVisible(false);c.face.setVisible(true);this.tweens.add({targets:c,scaleX:1,duration:140,ease:'Back.Out',onComplete:()=>this.afterFlip(c)})}})}
    afterFlip(c){if(!this.first){this.first=c;this.lock=false;return}const a=this.first;this.first=null;if(a.card.s===c.card.s){a.card.done=c.card.done=true;this.matched++;sparkle(this,c.x,c.y);sparkle(this,a.x,a.y);this.progress.setText(`${this.matched} / 6 pairs`);this.lock=false;if(this.matched===6){const elapsed=performance.now()-this.started;reward('pairs',20,elapsed);message(this,'Garden complete · +20 Berries and +1 Super Berry ✦','#ffe397');this.time.delayedCall(850,()=>sparkle(this,W/2,380,COLORS.gold,28))}}else{this.time.delayedCall(520,()=>{[a,c].forEach(card=>this.tweens.add({targets:card,scaleX:.04,duration:100,onComplete:()=>{card.card.open=false;card.face.setVisible(false);card.back.setVisible(true);this.tweens.add({targets:card,scaleX:1,duration:120})}}));this.time.delayedCall(250,()=>this.lock=false)})}}
  }

  class WordsScene extends Phaser.Scene{
    constructor(){super('words')}
    create(){header(this,'Word Garden','Grow four words, one little letter bed at a time');this.started=performance.now();this.words=Phaser.Utils.Array.Shuffle(['BERRY','HONEY','CLOUD','HEART','BLOOM','COZY','MOON','PETAL','HUGS','GLOW']).slice(0,4);this.round=0;this.score=0;this.timer=label(this,580,120,'0.0s',20,'#e9ffe5');this.flowers=[];for(let i=0;i<4;i++){this.add.circle(220+i*95,145,23,0x355e43,1);this.flowers.push(label(this,220+i*95,145,'·',28,'#ccead2'))}this.drawRound();}
    update(){this.timer?.setText(((performance.now()-this.started)/1000).toFixed(1)+'s')}
    drawRound(){this.children.getAll().filter(x=>x.getData?.('round')).forEach(x=>x.destroy());if(this.round>=this.words.length)return this.finish();const word=this.words[this.round],letters=Phaser.Utils.Array.Shuffle(word.split(''));this.answer='';this.letterObjs=[];const title=label(this,W/2,220,`${word.length} letter bloom`,22,'#dbffd9');title.setData('round',1);const slots=label(this,W/2,278,'_ '.repeat(word.length).trim(),34,'#fff');slots.setData('round',1);this.slotText=slots;const cols=Math.min(5,letters.length);letters.forEach((ch,i)=>{const x=W/2-(cols-1)*66+(i%cols)*132,y=385+Math.floor(i/cols)*120;const b=pill(this,x,y,96,82,ch,()=>{if(b.getData('used'))return;b.setData('used',1);b.setAlpha(.32);this.answer+=ch;this.slotText.setText(this.answer.split('').join(' ')+' '+ '_ '.repeat(Math.max(0,word.length-this.answer.length)).trim());if(this.answer.length===word.length)this.checkWord(word)}, {color:COLORS.green,size:30});b.setData('round',1);this.letterObjs.push(b)});const reset=pill(this,W/2,630,180,50,'Reset letters',()=>this.drawRound(),{color:COLORS.purple,size:18});reset.setData('round',1)}
    checkWord(word){if(this.answer===word){this.flowers[this.round].setText('🌸');sparkle(this,W/2,285,COLORS.mint,16);this.round++;this.time.delayedCall(650,()=>this.drawRound())}else{this.cameras.main.shake(170,.006);message(this,'Not quite. Let the letters settle and try again ♡','#ffd7e5');this.time.delayedCall(650,()=>this.drawRound())}}
    finish(){const elapsed=performance.now()-this.started;reward('words',25,elapsed);label(this,W/2,350,'🌸  GARDEN GROWN  🌸',34,'#fff2b4');message(this,'+25 Berries and +1 Super Berry ✦','#fff2b4');pill(this,W/2,520,220,58,'New garden',()=>this.scene.restart(),{color:COLORS.green});sparkle(this,W/2,350,COLORS.gold,30)}
  }

  function c4Winner(board,who){const dirs=[[0,1],[1,0],[1,1],[1,-1]];for(let r=0;r<6;r++)for(let c=0;c<7;c++){if(board[r*7+c]!==who)continue;for(const[dR,dC]of dirs){let ok=true;for(let k=1;k<4;k++){const rr=r+dR*k,cc=c+dC*k;if(rr<0||rr>=6||cc<0||cc>=7||board[rr*7+cc]!==who){ok=false;break}}if(ok)return true}}return false}
  function c4Index(board,col){for(let r=5;r>=0;r--){const i=r*7+col;if(!board[i])return i}return-1}
  class FourScene extends Phaser.Scene{
    constructor(){super('four')}
    create(){header(this,'Berry Four','Drop glossy counters. Four in a row wins.');this.board=Array(42).fill(0);this.started=performance.now();this.busy=false;this.ended=false;this.timer=label(this,590,120,'0.0s',20,'#dce7ff');this.status=label(this,160,120,'Your turn 🍓',20,'#ffe0ea');this.cells=[];const bx=80,by=190,cw=80,ch=78;const bg=this.add.graphics();bg.fillStyle(0x244b96,.96);bg.fillRoundedRect(bx-18,by-18,cw*7+36,ch*6+36,34);bg.lineStyle(6,0x7da5ff,.7);bg.strokeRoundedRect(bx-18,by-18,cw*7+36,ch*6+36,34);for(let r=0;r<6;r++)for(let c=0;c<7;c++){const x=bx+c*cw+cw/2,y=by+r*ch+ch/2;const hole=this.add.circle(x,y,28,0x13254d,1);hole.setStrokeStyle(3,0xffffff,.08);this.cells[r*7+c]={x,y,hole,token:null}}for(let c=0;c<7;c++){const z=this.add.zone(bx+c*cw,by,cw,ch*6).setOrigin(0).setInteractive({useHandCursor:true});z.on('pointerdown',()=>this.playerMove(c))}pill(this,W/2,720,200,54,'New game',()=>this.scene.restart(),{color:COLORS.blue})}
    update(){if(!this.ended)this.timer?.setText(((performance.now()-this.started)/1000).toFixed(1)+'s')}
    playerMove(col){if(this.busy||this.ended)return;const idx=c4Index(this.board,col);if(idx<0)return;this.busy=true;this.drop(idx,1,()=>{if(c4Winner(this.board,1)){this.end(1);return}if(this.board.every(Boolean)){this.end(0);return}this.status.setText('Star is thinking… ⭐');this.time.delayedCall(420,()=>this.aiMove())})}
    aiMove(){let col=this.pickAi(),idx=c4Index(this.board,col);if(idx<0){col=[0,1,2,3,4,5,6].find(c=>c4Index(this.board,c)>=0)??0;idx=c4Index(this.board,col)}this.drop(idx,2,()=>{if(c4Winner(this.board,2)){this.end(2);return}if(this.board.every(Boolean)){this.end(0);return}this.status.setText('Your turn 🍓');this.busy=false})}
    pickAi(){const valid=[0,1,2,3,4,5,6].filter(c=>c4Index(this.board,c)>=0);for(const who of[2,1])for(const c of valid){const i=c4Index(this.board,c);this.board[i]=who;const win=c4Winner(this.board,who);this.board[i]=0;if(win)return c}const weighted=[3,3,2,4,1,5,0,6].filter(c=>valid.includes(c));return Phaser.Utils.Array.GetRandom(weighted.length?weighted:valid)}
    drop(idx,who,cb){this.board[idx]=who;const cell=this.cells[idx],col=idx%7;const token=this.add.circle(cell.x,120,26,who===1?COLORS.berry:COLORS.gold,1).setStrokeStyle(5,0xffffff,.26);cell.token=token;this.tweens.add({targets:token,y:cell.y,duration:280+Math.floor(idx/7)*45,ease:'Bounce.Out',onComplete:()=>{sparkle(this,cell.x,cell.y,who===1?COLORS.berry2:COLORS.gold,5);cb?.()}})}
    end(who){this.ended=true;this.busy=true;const ms=performance.now()-this.started;if(who===1){this.status.setText('Berry wins! 🍓');reward('four',30,ms);message(this,'+30 Berries and +1 Super Berry ✦','#ffe39b');sparkle(this,W/2,430,COLORS.gold,30)}else if(who===2){this.status.setText('Star wins this round ⭐');message(this,'A cosy rematch is waiting ♡','#dce7ff')}else{this.status.setText('Cosy draw ♡');bridge()?.drawReward?.(8);message(this,'Draw reward · +8 Berries','#ffe3ed')}}
  }

  class ColourScene extends Phaser.Scene{
    constructor(){super('colour')}
    create(){header(this,'Colour Studio','Paint freely with a soft Berry palette');this.started=performance.now();this.strokes=0;this.finished=false;this.color=0xee5a82;panel(this,W/2,390,610,520,0xfffbfd,.96,30);this.canvas=this.add.graphics();this.guide=this.add.graphics();this.guide.lineStyle(7,0xead7df,.65);this.guide.strokeCircle(W/2,355,145);this.guide.strokeCircle(W/2-55,335,16);this.guide.strokeCircle(W/2+55,335,16);this.guide.beginPath();this.guide.arc(W/2,385,65,0.2,Math.PI-.2);this.guide.strokePath();this.guide.lineStyle(9,0x98b77f,.55);this.guide.lineBetween(320,220,285,170);this.guide.lineBetween(400,220,435,170);this.last=null;this.input.on('pointerdown',p=>this.begin(p));this.input.on('pointermove',p=>this.move(p));this.input.on('pointerup',()=>this.last=null);const palette=[0xee5a82,0xf7a4ba,0xf4c85b,0x75a985,0x7c76c9,0x54a7c3];palette.forEach((c,i)=>{const x=140+i*88,y=690;const sw=this.add.circle(x,y,27,c,1).setStrokeStyle(4,0xffffff,.35).setInteractive({useHandCursor:true});sw.on('pointerdown',()=>{this.color=c;this.tweens.add({targets:sw,scale:1.22,duration:90,yoyo:true})})});pill(this,220,755,150,48,'Clear',()=>{this.canvas.clear();this.strokes=0},{color:COLORS.purple,size:18});pill(this,500,755,190,48,'Finish art',()=>this.finish(),{color:COLORS.berry,size:18})}
    inCanvas(p){return p.x>60&&p.x<660&&p.y>145&&p.y<635}
    begin(p){if(!this.inCanvas(p))return;this.last={x:p.x,y:p.y};this.strokes++}
    move(p){if(!p.isDown||!this.last||!this.inCanvas(p))return;this.canvas.lineStyle(15,this.color,.94);this.canvas.lineBetween(this.last.x,this.last.y,p.x,p.y);this.last={x:p.x,y:p.y}}
    finish(){if(this.finished)return;if(this.strokes<8){message(this,'Add a few more brush strokes first 🎨','#ffe0ea');return}this.finished=true;const elapsed=performance.now()-this.started;reward('colour',25,elapsed);sparkle(this,W/2,355,COLORS.gold,30);message(this,'Artwork finished · +25 Berries and +1 Super Berry ✦','#ffe39b')}
  }

  class FarmScene extends Phaser.Scene{
    constructor(){super('farm')}
    create(){header(this,'Strawberry Farm','Walk, plant, water, sleep and harvest');this.drawFarm()}
    state(){return bridge()?.getState?.()?.farm}
    drawFarm(){this.children.removeAll(true);header(this,'Strawberry Farm','Walk, plant, water, sleep and harvest');const f=this.state();if(!f){label(this,W/2,H/2,'Farm save unavailable',28);return}label(this,160,120,`Day ${f.day||1}`,20,'#dff1dc');label(this,355,120,`🌱 ${f.seeds||0} seeds`,20,'#dff1dc');label(this,560,120,`⚡ ${f.energy||0}/12`,20,'#dff1dc');const gridX=92,gridY=178,tile=66;const plots=f.plots||[];for(let y=0;y<8;y++)for(let x=0;x<8;x++){let type='grass';if(y===0&&x===6)type='house';else if(x===0||y===7)type='path';else if(x===7&&y<5)type='water';else if(x>=2&&x<=5&&y>=2&&y<=5)type='soil';const colors={grass:0x6fa36f,path:0xc2a57e,water:0x62a9c9,soil:0x8a6049,house:0x9b5d55};const rx=gridX+x*tile,ry=gridY+y*tile;const g=this.add.graphics();g.fillStyle(colors[type],1);g.fillRoundedRect(rx,ry,tile-5,tile-5,12);g.lineStyle(2,0xffffff,.12);g.strokeRoundedRect(rx,ry,tile-5,tile-5,12);const p=plots.find(q=>q.x===x&&q.y===y);let icon=type==='house'?'🏡':type==='water'?'💧':'';if(p)icon=p.ready?'🍓':p.watered?'💦':(p.stage||0)>0?'🌿':'🌱';if(f.x===x&&f.y===y)icon='🧑‍🌾';if(icon)label(this,rx+30,ry+30,icon,28);const z=this.add.zone(rx,ry,tile-5,tile-5).setOrigin(0).setInteractive({useHandCursor:true});z.on('pointerdown',()=>this.tapTile(x,y))}const ctx=bridge()?.farmContext?.()||{label:'Farm action'};label(this,W/2,725,ctx.title||'Farm plot',20,'#fff');pill(this,165,775,190,48,ctx.label||'Farm action',()=>{bridge()?.actions?.farmAct?.();this.time.delayedCall(60,()=>this.drawFarm())},{color:COLORS.berry,size:17});pill(this,365,775,160,48,'Sleep 🌙',()=>{bridge()?.actions?.farmSleep?.();this.time.delayedCall(60,()=>this.drawFarm())},{color:COLORS.purple,size:17});pill(this,555,775,190,48,'Buy seeds',()=>{bridge()?.actions?.farmBuySeeds?.();this.time.delayedCall(60,()=>this.drawFarm())},{color:COLORS.green,size:17})}
    tapTile(x,y){const f=this.state();if(!f)return;const dx=x-f.x,dy=y-f.y;if(Math.abs(dx)+Math.abs(dy)===1){bridge()?.actions?.farmMove?.(dx,dy);this.time.delayedCall(50,()=>this.drawFarm())}else{this.cameras.main.shake(80,.002)}}
  }

  class TogetherScene extends Phaser.Scene{
    constructor(){super('together');this.g=null;this.prevMove=-1;this.signalDraft=[]}
    init(data){this.g=data?.g||null}
    create(){this.draw()}
    sync(g){this.g=g;this.draw()}
    clear(){this.children.removeAll(true)}
    top(title,sub){header(this,title,sub)}
    draw(){if(!this.g)return;const g=this.g;this.clear();const sub=g.status==='finished'?'Round finished':(g.turn===bridge()?.getAccount?.()?.id?'Your move':'Partner move');this.top(g.title||'Play Together',sub);switch(g.type){case'ttt':return this.ttt(g);case'connect':return this.connect(g);case'rps':return this.rps(g);case'rescue':return this.rescue(g);case'signal':return this.signal(g);case'trails':return this.trails(g)}}
    ttt(g){const me=bridge()?.getAccount?.()?.id,x0=150,y0=190,s=140;panel(this,W/2,410,500,500,COLORS.panel,.74,34);for(let i=0;i<9;i++){const c=i%3,r=Math.floor(i/3),x=x0+c*s,y=y0+r*s;const bg=this.add.graphics();bg.fillStyle(0xffffff,.08);bg.fillRoundedRect(x,y,s-12,s-12,24);const v=g.board[i];if(v)label(this,x+s/2-6,y+s/2-6,v,54);const z=this.add.zone(x,y,s-12,s-12).setOrigin(0).setInteractive({useHandCursor:true});z.on('pointerdown',()=>{if(g.turn===me&&!v&&!g.winner)bridge()?.actions?.mpTttMove?.(i)})}label(this,W/2,700,g.winner?'Round complete ♡':g.turn===me?'Your turn 🍓':'Partner is thinking…',22,'#ffe1ec')}
    connect(g){const me=bridge()?.getAccount?.()?.id,bx=84,by=190,cw=79,ch=72;const bg=this.add.graphics();bg.fillStyle(0x244b96,.96);bg.fillRoundedRect(bx-18,by-18,cw*7+36,ch*6+36,34);bg.lineStyle(6,0x7da5ff,.7);bg.strokeRoundedRect(bx-18,by-18,cw*7+36,ch*6+36,34);const move=Number(g.moveSeq||0);for(let r=0;r<6;r++)for(let c=0;c<7;c++){const i=r*7+c,x=bx+c*cw+cw/2,y=by+r*ch+ch/2,v=g.board[i];this.add.circle(x,y,26,v?(v==='🍓'?COLORS.berry:COLORS.gold):0x13254d,1).setStrokeStyle(3,0xffffff,v?.24:.08);if(v&&i===g.lastDrop&&move!==this.prevMove){const tok=this.add.circle(x,100,26,v==='🍓'?COLORS.berry:COLORS.gold,1).setStrokeStyle(4,0xffffff,.24);this.tweens.add({targets:tok,y,duration:300+r*45,ease:'Bounce.Out',onComplete:()=>sparkle(this,x,y,v==='🍓'?COLORS.berry2:COLORS.gold,7)})}}for(let c=0;c<7;c++){const z=this.add.zone(bx+c*cw,by,cw,ch*6).setOrigin(0).setInteractive({useHandCursor:true});z.on('pointerdown',()=>{if(g.turn===me&&!g.winner)bridge()?.actions?.mpConnectMove?.(c)})}this.prevMove=move;label(this,W/2,690,g.winner?'Four Together complete ♡':g.turn===me?'Your drop 🍓':'Partner is dropping…',22,'#dce7ff')}
    rps(g){const me=bridge()?.getAccount?.()?.id,choices=[['rock','🪨'],['paper','📄'],['scissors','✂️']];choices.forEach(([k,icon],i)=>{const x=160+i*200,y=360;const selected=g.choices?.[me]===k;const c=pill(this,x,y,150,150,icon,()=>bridge()?.actions?.mpRpsChoose?.(k),{color:selected?COLORS.berry:COLORS.panel2,size:58});if(g.choices?.[me])c.disableInteractive()});label(this,W/2,540,g.winner?`You: ${g.choices?.[me]||'—'} · Partner: ${g.choices?.[bridge()?.otherId?.(g)]||'—'}`:'Choose secretly. Reveal happens together.',22,'#ffe1ec',{wrap:600})}
    rescue(g){const r=g.rescue,map=bridge()?.rescueFlat?.(g)||'',me=bridge()?.getAccount?.()?.id;label(this,180,120,`✨ ${r.lights.length}/3`,20,'#e8fff0');label(this,525,120,`Lantern ${r.energy}/${r.maxEnergy}`,20,'#ffe6a9');const x0=135,y0=190,s=76;for(let i=0;i<36;i++){const c=i%6,rr=Math.floor(i/6),x=x0+c*s,y=y0+rr*s,t=map[i]||'.',reachable=g.turn===me&&g.status==='active'&&!g.winner&&Math.abs(Math.floor(r.pos/6)-rr)+Math.abs((r.pos%6)-c)===1&&t!=='#';const colors={'#':0x45424c,'m':0x557d8e,'l':0x5b855a,'f':0x6f9a69,'H':0x9a7654,'.':0x628967,'S':0x628967};const box=this.add.graphics();box.fillStyle(colors[t]||0x628967,1);box.fillRoundedRect(x,y,s-7,s-7,14);if(reachable){box.lineStyle(4,0xffe19a,.9);box.strokeRoundedRect(x,y,s-7,s-7,14)}let icon=t==='#'?'🪨':t==='m'?'💧':t==='H'?'🏡':t==='l'&&!r.lights.includes(i)?'✨':t==='f'&&!r.flowers.includes(i)?'🌼':'';if(i===r.pos)icon='🍓';if(icon)label(this,x+34,y+34,icon,28);const z=this.add.zone(x,y,s-7,s-7).setOrigin(0).setInteractive({useHandCursor:true});z.on('pointerdown',()=>{if(reachable)bridge()?.actions?.rescueMove?.(i)})}label(this,W/2,700,g.turn===me?'Guide the shared Berry':'Partner is choosing the next step…',20,'#e8fff0')}
    signal(g){const me=bridge()?.getAccount?.()?.id,isClue=bridge()?.signalClueId?.(g)===me,s=g.signal;label(this,W/2,125,`Transmission ${Math.min(s.stage,s.totalStages)} / ${s.totalStages}`,20,'#e8e5ff');if(isClue){label(this,W/2,245,'YOUR SECRET SIGNAL',20,'#ffd7e5');const icons=(s.pattern||[]).map(id=>({rose:'🌸',moon:'🌙',mint:'🍃',gold:'⭐'}[id]||'?'));label(this,W/2,355,icons.join('  '),52,'#fff');label(this,W/2,485,'Describe the order to your partner.\nThey enter what they hear.',23,'#e7dcff',{wrap:580})}else{label(this,W/2,205,'DECODE THE SIGNAL',20,'#ffd7e5');const map=[['rose','🌸'],['moon','🌙'],['mint','🍃'],['gold','⭐']];label(this,W/2,290,(this.signalDraft.map(x=>map.find(k=>k[0]===x)?.[1]).join('  ')||'·   ·   ·   ·'),46,'#fff');map.forEach(([id,icon],i)=>pill(this,140+i*145,420,105,92,icon,()=>{if(this.signalDraft.length<4){this.signalDraft.push(id);this.draw()}},{color:[0xbd5f89,0x766db8,0x6e9e7f,0xd2a847][i],size:38}));pill(this,250,565,170,50,'Undo',()=>{this.signalDraft.pop();this.draw()},{color:COLORS.purple,size:18});pill(this,470,565,190,50,'Transmit',()=>{if(this.signalDraft.length===4){bridge()?.actions?.signalSubmitValues?.([...this.signalDraft]);this.signalDraft=[]}},{color:COLORS.berry,size:18})}}
    trails(g){const t=g.trails,me=bridge()?.getAccount?.()?.id,x0=165,y0=190,s=82;for(let i=0;i<25;i++){const c=i%5,r=Math.floor(i/5),x=x0+c*s,y=y0+r*s,owner=t.owners[i],host=owner===g.hostId,val=[1,2,1,3,0,1,1,2,1,2,2,3,1,2,1,1,2,3,1,2,0,3,1,2,1][i]||1,can=!owner&&g.turn===me&&bridge()?.trailAdjacentOwned?.(t.owners,i,me)&&g.status==='active'&&!g.winner;const box=this.add.graphics();box.fillStyle(owner?(host?0xb83e68:0x655aab):0x456a58,1);box.fillRoundedRect(x,y,s-7,s-7,16);if(can){box.lineStyle(4,0xffe5a2,.9);box.strokeRoundedRect(x,y,s-7,s-7,16)}const icon=owner?(host?'🍓':'🌙'):(val===3?'💎':val===2?'🌸':'');if(icon)label(this,x+37,y+37,icon,28);const z=this.add.zone(x,y,s-7,s-7).setOrigin(0).setInteractive({useHandCursor:true});z.on('pointerdown',()=>{if(can)bridge()?.actions?.trailClaim?.(i)})}label(this,W/2,650,`${t.moves}/${t.maxMoves} garden claims`,20,'#dff4df');label(this,W/2,695,g.turn===me?'Grow your trail':'Partner is growing…',22,'#ffe0eb')}
  }

  function sceneFor(key){return {pairs:PairsScene,words:WordsScene,four:FourScene,colour:ColourScene,farm:FarmScene}[key]}
  function launchSolo(key,pane){
    if(key==='together')return;
    const Scene=sceneFor(key);if(!Scene||!pane)return false;
    const stage=stageFor(pane,key);
    if(!phaserReady()){stage.innerHTML='<div class="berry-arcade-loading"><div><b>🍓 Berry Arcade</b>Game engine is loading. The classic game remains available below.</div></div>';pane.classList.remove('beta-phaser');return false}
    if(soloKey===key&&soloGame&&stage.querySelector('canvas'))return true;
    destroy(soloGame);soloGame=null;soloKey=key;stage.innerHTML='';soloGame=new Phaser.Game(makeConfig(stage,new Scene()));return true
  }
  function resumeActiveSolo(){const active=document.querySelector('[data-game].active');if(!active)return;const key=active.dataset.game;if(key==='together')return;const pane=document.getElementById('game'+({pairs:'Pairs',words:'Words',four:'Four',colour:'Colour',farm:'Farm'}[key]||''));if(pane)launchSolo(key,pane)}
  function renderMultiplayer(g,board){
    if(!g||!board||!phaserReady())return false;board.classList.add('beta-phaser-board');let stage=board.querySelector('.berry-arcade-stage');if(!stage){stage=document.createElement('div');stage.className='berry-arcade-stage';board.appendChild(stage)}const art=window.getBerryGameArt?.(g.type)?.src||window.getBerryGameArt?.(g.type==='connect'?'four':g.type)?.src;if(art){stage.style.backgroundImage=`linear-gradient(180deg,rgba(16,8,16,.50),rgba(16,8,16,.80)),url("${art}")`;stage.style.backgroundSize='cover'}if(mpId!==g.id||!mpGame||!stage.querySelector('canvas')){destroy(mpGame);mpId=g.id;stage.innerHTML='';mpGame=new Phaser.Game(makeConfig(stage,TogetherScene));setTimeout(()=>{const s=mpGame?.scene?.getScene?.('together');if(s){s.g=g;s.draw?.()}},80)}else{const s=mpGame.scene.getScene('together');if(s){s.g=g;s.draw?.()}}return true
  }
  function leaveMultiplayer(){destroy(mpGame);mpGame=null;mpId=''}
  window.BerryArcade={launchSolo,resumeActiveSolo,renderMultiplayer,leaveMultiplayer,destroyAll(){destroy(soloGame);destroy(mpGame);soloGame=mpGame=null;soloKey=mpId=''}};
})();
